name: Build Static Wget for OpenWrt (aarch64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET_TRIPLE: aarch64-linux-musl
      TOOLCHAIN_URL: https://github.com/userdocs/qbt-musl-cross-make/releases/latest/download/aarch64-aarch64-linux-musl.tar.xz

    steps:
    - name: Download musl-cross toolchain
      run: |
        wget -O toolchain.tar.xz "$TOOLCHAIN_URL"
        tar xf toolchain.tar.xz
        echo "$PWD/aarch64-linux-musl/bin" >> $GITHUB_PATH

    - name: Install build tools
      run: |
        sudo apt update
        sudo apt install -y build-essential wget git autoconf automake \
          libtool pkg-config

    - name: Download wget source
      run: |
        wget https://ftp.gnu.org/gnu/wget/wget-1.21.4.tar.gz
        tar xf wget-1.21.4.tar.gz

    - name: Compile wget statically
      run: |
        cd wget-1.21.4
        ./configure \
          --host=${TARGET_TRIPLE} \
          --with-ssl=openssl \
          --disable-shared --enable-static \
          CC=${TARGET_TRIPLE}-gcc LDFLAGS="-static"
        make -j$(nproc)

    - name: Upload wget binary
      uses: actions/upload-artifact@v4
      with:
        name: wget-static-aarch64
        path: wget-1.21.4/src/wget
