name: Build static wget (aarch64-musl)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET_TRIPLE: aarch64-linux-musl
      TOOLCHAIN_URL: https://github.com/userdocs/qbt-musl-cross-make/releases/latest/download/aarch64-linux-musl.tar.xz

    steps:
    - name: Download musl-cross toolchain
      run: |
        wget -O toolchain.tar.xz "$TOOLCHAIN_URL"
        tar xf toolchain.tar.xz -C .
        export PATH="$PWD/aarch64-linux-musl/bin:$PATH"

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential wget git autoconf automake libtool pkg-config

    - name: Clone wget source
      run: |
        git clone https://git.savannah.gnu.org/git/wget.git
        cd wget
        git checkout v1.21.4

    - name: Build static wget
      run: |
        cd wget
        ./bootstrap
        CC=${TARGET_TRIPLE}-gcc ./configure \
          --host=${TARGET_TRIPLE} \
          --with-ssl=openssl \
          --disable-shared --enable-static LDFLAGS="-static"
        make -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wget-static-aarch64
        path: wget/src/wget
