name: Build Static Wget (aarch64-musl)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TARGET_TRIPLE: aarch64-linux-musl
      TOOLCHAIN_URL: https://github.com/userdocs/qbt-musl-cross-make/releases/latest/download/aarch64-aarch64-linux-musl.tar.xz

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential wget git pkg-config

    - name: Download & extract musl-cross toolchain
      run: |
        wget -O toolchain.tar.xz "$TOOLCHAIN_URL"
        tar xf toolchain.tar.xz
        echo "$PWD/aarch64-linux-musl/bin" >> $GITHUB_PATH

    - name: Download wget source
      run: |
        wget https://ftp.gnu.org/gnu/wget/wget-1.21.4.tar.gz
        tar xf wget-1.21.4.tar.gz

    - name: Configure & build wget
      run: |
        cd wget-1.21.4
        # ensure config.guess is here
        ls config.guess
        # set cross-compiler path
        export PATH="$PWD/../aarch64-linux-musl/bin:$PATH"
        # build static with OpenSSL
        ./configure \
          --build=$(./config.guess) \
          --host=${TARGET_TRIPLE} \
          --with-ssl=openssl \
          CC=${TARGET_TRIPLE}-gcc \
          CFLAGS="-static -I$PWD/../aarch64-linux-musl/sysroot/usr/include" \
          LDFLAGS="-static -L$PWD/../aarch64-linux-musl/sysroot/usr/lib"
        make -j$(nproc)

    - name: Upload static wget
      uses: actions/upload-artifact@v4
      with:
        name: wget-static-aarch64
        path: wget-1.21.4/src/wget
