name: Build Static Wget (aarch64-musl)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential wget git autoconf automake libtool pkg-config

    - name: Download musl-cross toolchain
      run: |
        # 注意：这里用我确认存在的可靠版本，你可以换成你信任的工具链地址
        wget -O toolchain.tar.xz https://github.com/sabotage-linux/sabotage/releases/download/20231011/aarch64-musl-cross-20231011.tar.xz
        tar xf toolchain.tar.xz
        echo "$PWD/aarch64-musl-cross-20231011/bin" >> $GITHUB_PATH

    - name: Download wget source code
      run: |
        wget https://ftp.gnu.org/gnu/wget/wget-1.21.4.tar.gz
        tar xf wget-1.21.4.tar.gz

    - name: Configure and build wget
      run: |
        cd wget-1.21.4
        # 确认 config.guess 存在
        ls -l config.guess

        export PATH="$PWD/../aarch64-musl-cross-20231011/bin:$PATH"

        ./configure \
          --build=$(./config.guess) \
          --host=aarch64-linux-musl \
          --with-ssl=openssl \
          CC=aarch64-linux-musl-gcc \
          CFLAGS="-static -I$PWD/../aarch64-musl-cross-20231011/aarch64-linux-musl/sysroot/usr/include" \
          LDFLAGS="-static -L$PWD/../aarch64-musl-cross-20231011/aarch64-linux-musl/sysroot/usr/lib"

        make -j$(nproc)

    - name: Upload built wget binary
      uses: actions/upload-artifact@v4
      with:
        name: wget-static-aarch64
        path: wget-1.21.4/src/wget
