
: Build Static wget
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenWrt SDK
        run: |
          SDK_URL="https://mirror-03.infra.openwrt.org/releases/23.05.4/targets/mediatek/mt7622/openwrt-sdk-23.05.4-mediatek-mt7622_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          wget -q $SDK_URL -O sdk.tar.xz
          tar xf sdk.tar.xz
          SDK_DIR=$(tar tf sdk.tar.xz | head -1 | cut -f1 -d"/")
          mv $SDK_DIR sdk
          echo "SDK_PATH=$(pwd)/sdk" >> $GITHUB_ENV
          ls -l ${{ env.SDK_PATH }}/include/  # 验证目录结构

      - name: Patch SDK
        run: |
          cd ${{ env.SDK_PATH }}
          [ -f include/defaults.mk ] || (echo "Error: defaults.mk missing" && exit 1)
          sed -i 's/--disable-static/--enable-static/g' include/defaults.mk
          echo "CONFIG_PACKAGE_wget=y" >> .config
          echo "CONFIG_WGET_SSL=y" >> .config

      - name: Compile wget
        run: |
          cd ${{ env.SDK_PATH }}
          make defconfig
          make package/wget/compile -j$(nproc) V=s
          find bin -name "wget" -type f -exec cp {} ./ \;

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wget-static
          path: ${{ env.SDK_PATH }}/wget
