name: Build Static Wget for aarch64_cortex-a53

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up cross-compilation environment for aarch64
      run: |
        sudo apt update
        sudo apt install -y build-essential libssl-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gettext gperf

    - name: Download and build wget for aarch64
      run: |
        git clone https://git.savannah.gnu.org/git/wget.git
        cd wget
        ./bootstrap
        ./configure --host=aarch64-linux-gnu --with-ssl=openssl --disable-ntlm
        make
        make install DESTDIR=/tmp/aarch64-wget

    - name: Zip the wget binary
      run: |
        cd /tmp
        zip -r /tmp/wget-aarch64-static.zip aarch64-wget/usr/local/bin/wget

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: /tmp/wget-aarch64-static.zip
