name: Build Static Wget (aarch64-musl)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TARGET_TRIPLE: aarch64-linux-musl
      TOOLCHAIN_URL: https://github.com/userdocs/qbt-musl-cross-make/releases/latest/download/aarch64-aarch64-linux-musl.tar.xz

    steps:
    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential wget git autoconf automake libtool pkg-config

    - name: Download and extract musl-cross toolchain
      run: |
        wget -O toolchain.tar.xz "$TOOLCHAIN_URL"
        tar xf toolchain.tar.xz
        echo "$PWD/aarch64-linux-musl/bin" >> $GITHUB_PATH

    - name: Set environment variables
      run: |
        echo "CFLAGS=-static -I$GITHUB_WORKSPACE/aarch64-linux-musl/aarch64-linux-musl/sysroot/usr/include" >> $GITHUB_ENV
        echo "LDFLAGS=-static -L$GITHUB_WORKSPACE/aarch64-linux-musl/aarch64-linux-musl/sysroot/usr/lib" >> $GITHUB_ENV

    - name: Download wget source
      run: |
        wget https://ftp.gnu.org/gnu/wget/wget-1.21.4.tar.gz
        tar xf wget-1.21.4.tar.gz

    - name: Configure wget (cross compile)
      run: |
        cd wget-1.21.4
        ./configure \
          --build=$(./config.guess) \
          --host=${TARGET_TRIPLE} \
          --with-ssl=openssl \
          CC=${TARGET_TRIPLE}-gcc

    - name: Compile wget
      run: |
        cd wget-1.21.4
        make -j$(nproc)

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: wget-static-aarch64
        path: wget-1.21.4/src/wget
