name: Static wget for OpenWrt (aarch64_cortex-a53_neon-vfpv4)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential autoconf automake libtool \
            pkg-config libssl-dev zlib1g-dev wget git gcc-aarch64-linux-gnu \
            autopoint gperf autoconf-archive

    - name: Clone wget
      run: |
        git clone https://git.savannah.gnu.org/git/wget.git
        cd wget
        git checkout v1.21.4

    - name: Build static wget for aarch64
      run: |
        cd wget
        ./bootstrap
        ./configure --host=aarch64-linux-gnu --with-ssl=openssl \
          --disable-shared --enable-static LDFLAGS="-static"
        make -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: static-wget-aarch64
        path: wget/src/wget
