name: Build Static wget for aarch64
on: [push] # 触发条件

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OpenWrt SDK
        run: |
          SDK_URL="https://mirror-03.infra.openwrt.org/releases/23.05.4/targets/mediatek/mt7622/openwrt-sdk-23.05.4-mediatek-mt7622_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          wget $SDK_URL
          tar xf openwrt-sdk-*.tar.xz
          cd openwrt-sdk-*
          echo SDK_PATH=$PWD >> $GITHUB_ENV

      - name: Build wget
        run: |
          cd ${{ env.SDK_PATH }}
          # 启用静态编译选项
          cp -f include/defaults.mk include/defaults.mk.bak
          sed -i 's/--disable-static/--enable-static/g' include/defaults.mk
          
          # 编译 wget（含 SSL 支持）
          make package/network/utils/wget/compile V=sc
          
          # 提取编译产物
          find bin -name "wget" -exec cp {} $PWD \;
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: wget-static-aarch64
          path: ${{ env.SDK_PATH }}/wget
